# Project information
site_name: liufr
site_description: Fengrui Liu's personal CV
site_author: liufr
site_url: https://liufr.com

# Repository
repo_name: Fengrui-Liu/myCV
repo_url: https://github.com/Fengrui-Liu/myCV

# Copyright
copyright: Copyright &copy; 2021

# Configuration
theme:
    name: material
    custom_dir: docs/overrides
    language: en
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    logo: img/blog.png
    favicon: img/blog.png
    features:
        - navigation.tabs
        - navigation.instant

# Extras
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/online-ml/river


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: false
  - footnotes
  - toc:
        permalink: true
        toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

  - js/version-select.js
extra_css:
  - stylesheets/extra.css
  - css/version-select.css
